import 'package:flutter/material.dart';

String thekey = 'fef398fcb430ff38d3fc782d15eb1f7f';

//PRIVATE INFO PRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFOPRIVATE INFO